# Generated by Django 5.2.1 on 2025-05-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('FANTASY', 'Fantasy'), ('SCIENCE FICTION', 'Science Fiction'), ('THRILLER/SUSPENSE', 'Thriller/Suspense'), ('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('ACTION AND ADVENTURE', 'Action and Adventure'), ('CLASSICS', 'Classics'), ('CHILDREN AND YOUNG ADULT', 'Children and Young Adult'), ('SPECULATIVE FICTION', 'Speculative Fiction'), ('BIOGRAPHY', 'Biography'), ('AUTOBIOGRAPHY', 'Autobiography'), ('HISTORY', 'History'), ('SCIENCE', 'Science'), ('SELF-HELP', 'Self-Help'), ('COOKING', 'Cooking'), ('GASTRONOMY', 'Gastronomy'), ('TRAVEL', 'Travel'), ('ECONOMICS', 'Economics'), ('ART', 'Art'), ('RELIGION', 'Religion'), ('POLITICS', 'Politics'), ('INVESTIGATIVE JOURNALISM', 'Investigative Journalism'), ('ESSAYS', 'Essays'), ('MANUALS', 'Manuals')], max_length=50)),
                ('authors', models.ManyToManyField(related_name='books', to='bookcontrol.author')),
            ],
        ),
    ]
